version: "3.8"

services:
  frontend:
    image: node:22-slim
    working_dir: /app
    container_name: frontend
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app
    restart: always
    command: bash -c "apt-get update && apt-get install -y && npm i && npm run dev -- --host 0.0.0.0"
